groups:
  - name: host_alerts
    rules:
      - alert: HighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 0m
        labels:
          severity: warning
          alert_type: "Cảnh báo quá tải CPU"
          alert_msg: 'CPU host đang ở mức {{ printf "%.2f" $value }}%.'

      - alert: HighMemoryUsage
        expr: 100 - ((avg_over_time(node_memory_MemAvailable_bytes[5m]) / avg_over_time(node_memory_MemTotal_bytes[5m])) * 100) > 80
        for: 0m
        labels:
          severity: warning
          alert_type: "Cảnh báo đầy RAM"
          alert_msg: 'RAM máy chủ {{ $labels.instance }} đang ở mức {{ printf "%.2f" $value }}%.'
